CONFIG_SHELL=y

# CONFIG_DEBUG_THREAD_INFO=y
# CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_MAIN_STACK_SIZE=2048

CONFIG_GPIO=y
CONFIG_SENSOR=y

CONFIG_VL53L5CX=y
CONFIG_VL53L5CX_RESOLUTION_4X4=y
CONFIG_VL53L5CX_RANGING_FREQ=10

CONFIG_LOG=y
CONFIG_I2C_LOG_LEVEL_DBG=y
